# Generated by Django 5.2.5 on 2025-08-23 22:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('subjects_taught', models.CharField(max_length=250, verbose_name='преподаваемые предметы')),
                ('info', models.TextField(verbose_name='Дополнительная информация')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия курса')),
                ('info', models.TextField(verbose_name='Информация о курсе')),
                ('duration', models.CharField(max_length=100, verbose_name='Длительность занятий')),
                ('price', models.CharField(max_length=100, verbose_name='Стоимость курса')),
                ('age_category', models.CharField(max_length=100, verbose_name='Возрастная категория')),
                ('image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Курсы',
            },
        ),
    ]
